export const userRows = [
  {
    id: 1,
    Name: 'Vanesa',
    UserName: 'Vanesa88',
    Suscription: 'Free',
    Status: 'Writer',
    Books: '3',
    Email: 'vancig88@gmail.com',
  },
  {
    id: 2,
    Name: 'Lorena',
    UserName: 'Lore.45',
    Suscription: 'Free',
    Status: 'Writer',
    Books: '1',
    Email: 'lore.lore@gmail.com',
  },
  {
    id: 3,
    Name: 'Mariano',
    UserName: 'Mariano Conte',
    Suscription: 'Premium',
    Status: 'User',
    Books: '0',
    Email: 'marian@hotmail.com',
  },
  {
    id: 4,
    Name: 'Vanesa',
    UserName: 'Vanesa88',
    Suscription: 'Free',
    Status: 'User',
    Books: '3',
    Email: 'vancig88@gmail.com',
  },
  {
    id: 5,
    Name: 'Vanesa',
    UserName: 'Vanesa88',
    Suscription: 'Premium',
    Status: 'User',
    Books: '0',
    Email: 'vancig88@gmail.com',
  },
]
